services:
  eleventy:
    image: femtopixel/eleventy
    volumes:
      - "./:/var/www"
    working_dir: "/var/www"
  server:
    image: femtopixel/eleventy
    command: --serve --output=docs
    volumes:
      - "./:/var/www"
    working_dir: "/var/www"
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
